# .streamlit/secrets.toml

# Your API Key from the original script
ROBOFLOW_API_KEY = "qBeCWYGbEVDEKAyyy2um"

# Your Project ID from the original script
ROBOFLOW_PROJECT = "coin_recognition-0vii0"

# Your Model Version from the original script
ROBOFLOW_VERSION = 1